### ISSUE TITLE
A license issue

### ISSUE THREAD

**Issue by VulpesStella** [WolfGenerals/PetPhrasePlus#1]
上游项目 PetPhrase 遵循 GNU AGPL v3许可。
如果你承认本项目是基于上游项目修改的，应使用相同的许可证。

实际上因为代码相似度不高，不改应该也没事，单纯提个建议awa（

**Comment by WolfGenerals** [comment]
找到了，不过是完全重新写了一个mod，只不过实在是像(毕竟实现的功能类似)，许可不出意外应该会随着下一个版本更新
