### ISSUE TITLE
[BUG] 口癖 mod 输入单个标点符号会崩端

### ISSUE THREAD

**Issue by ESEAbsolute** [WolfGenerals/PetPhrasePlus#2]
## 问题描述

发出一串仅有标点符号组成的消息，如「（」或「（（（（（」，会导致游戏崩溃闪退。

初次发现是咱在标点符号前和标点符号后设置为「空」的时候。接下来经过测试，在标点符号前和标点符号后设置为「a」的时候也会闪退，大概是与这两个设置无关的，是 mod 本身的问题 QAQ

## 复现方法

在游戏中打开聊天框，并输入一串仅有标点符号组成的话，并按下回车

## 原因分析

怀疑是 [Util.java 中 endInner() 函数](https://github.com/WolfGenerals/PetPhrasePlus/blob/7ec7ff2a5aef84f56f85ea61d804ae226d1f3ac5/src/main/java/com/github/wolfgenerals/petphraseplus/Util.java#L42) 的递归边界判断问题。

```java
        if (punctuations.contains(original.charAt(subscript - 1))) {
            m = endInner(original, endInner, subscript - 1);
        }
```
这里个人感觉，如果标点符号一直向前遍历直到字符串下标为 0 时，再次访问并递归 subscript - 1 会出现问题，导致游戏崩溃。

不知道将第 41 行中 if 内的内容改成 `punctuations.contains(original.charAt(subscript - 1)) && subscript > 0` 是否会解决问题。

## 更多信息

游戏版本：Minecraft 1.18.2
mod 版本：[1.18.2 1.1.0](https://github.com/WolfGenerals/PetPhrasePlus/releases/tag/fabric1.1.0)
Fabric 版本：0.14.12
mod 配置：（因为 Github 限制了上传文件类型，咱将 .properties 后缀改成了 .txt）[petphraseplus.txt](https://github.com/WolfGenerals/PetPhrasePlus/files/10368363/petphraseplus.txt)

## 崩溃报告

这个是与很多 mod 一起工作时崩溃的错误报告（PCL2 自动生成）：[错误报告-2023-1-8_19.54.44.zip](https://github.com/WolfGenerals/PetPhrasePlus/files/10368320/-2023-1-8_19.54.44.zip)  
这个是仅仅使用 PetPhrasePlus 1.1.0 和 cloth config 6.4.87 和 fabric api 0.67.0 时崩溃的错误报告（PCL2 自动生成）：[错误报告-2023-1-8_20.07.59.zip](https://github.com/WolfGenerals/PetPhrasePlus/files/10368359/-2023-1-8_20.07.59.zip)

**Comment by WolfGenerals** [comment]
尝试修复了

**Comment by ESEAbsolute** [comment]
> 尝试修复了

万分感谢，辛苦啦
